# Generated by Django 4.1.5 on 2023-01-18 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('agency_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oln_state_passenger', models.CharField(max_length=20)),
                ('oln_number_passenger', models.CharField(max_length=30)),
                ('class_oln_passenger', models.CharField(max_length=20)),
                ('cdl_passenger', models.BooleanField(default=False)),
                ('fullname_passenger', models.CharField(max_length=180)),
                ('dob_passenger', models.DateField()),
                ('hair_passenger', models.CharField(blank=True, max_length=25)),
                ('eyes_passenger', models.CharField(blank=True, max_length=25)),
                ('height_passenger', models.CharField(blank=True, max_length=10)),
                ('address_passenger', models.CharField(blank=True, max_length=180)),
                ('city_passenger', models.CharField(max_length=30)),
                ('state_passenger', models.CharField(max_length=25)),
                ('phone_passenger', models.CharField(max_length=25)),
                ('email_passenger', models.EmailField(max_length=254)),
                ('violation_datetime', models.DateTimeField()),
                ('route', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('factor_crash', models.BooleanField()),
                ('factor_passenger', models.BooleanField()),
                ('factor_spanish_speaker', models.BooleanField()),
                ('factor_in_car_video', models.BooleanField()),
                ('factor_construction_zone', models.BooleanField()),
                ('factor_body_camera', models.BooleanField()),
                ('factor_school_zone', models.BooleanField()),
                ('factor_workers_present', models.BooleanField()),
                ('officer_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=12)),
                ('color', models.CharField(max_length=30)),
                ('make', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('model_vehicle', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=185)),
                ('citation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='citation_violation', to='civiapp.citation')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='citation',
            name='gender_passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='civiapp.gender'),
        ),
        migrations.AddField(
            model_name='citation',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='civiapp.officer'),
        ),
        migrations.AddField(
            model_name='citation',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='civiapp.vehicletype'),
        ),
    ]
