# Generated by Django 4.1.5 on 2023-01-18 23:32

from django.db import migrations


def gender_initial(apps, schema_editor):
    gender_model = apps.get_model('civiapp', 'Gender')
    gender_model.objects.bulk_create([
        gender_model(name='FEMALE'),
        gender_model(name='MALE'),
        gender_model(name='NONE')
    ])


def revert_gender_initial(apps, schema_editor):
    gender_model = apps.get_model('civiapp', 'Gender')
    gender_model.objects.all().delete()


def initial_superuser(apps, schema_editor):
    super_user = apps.get_model('auth', 'User')
    super_user.objects.create_superuser(
        username='admin',
        password='P@ssw0rd'
    )


def revert_initial_superuser(apps, schema_editor):
    super_user = apps.get_model('auth', 'User')
    super_user.objects.get(username='admin').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('civiapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(gender_initial, revert_gender_initial),
        migrations.RunPython(initial_superuser, revert_initial_superuser)
    ]
