# Generated by Django 4.1.5 on 2023-01-19 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civiapp', '0003_clerk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='citation',
            name='violation_datetime',
        ),
        migrations.AddField(
            model_name='citation',
            name='color',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citation',
            name='make',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citation',
            name='model_vehicle',
            field=models.CharField(default='', max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citation',
            name='vin',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citation',
            name='violation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='citation',
            name='violation_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='citation',
            name='year',
            field=models.PositiveSmallIntegerField(default=1900),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VehicleType',
        ),
    ]
