# Generated by Django 4.1.5 on 2023-01-19 22:23

from django.db import migrations
from django.db.models import Q


def groups_initial(apps, schema_editor):
    group_model = apps.get_model('auth', 'Group')
    group_model.objects.bulk_create([
        group_model(name='OFFICER'),
        group_model(name='CLERK')
    ])


def revert_group(apps, schema_editor):
    group_model = apps.get_model('auth', 'Group')
    group_model.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('civiapp', '0005_clerk_agency_officer_agency'),
    ]

    operations = [
        migrations.RunPython(groups_initial, revert_group)
    ]
