# Generated by Django 4.1.5 on 2023-01-19 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('civiapp', '0006_auto_20230119_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerk',
            name='rol',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='auth.group'),
        ),
        migrations.AddField(
            model_name='officer',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='auth.group'),
        ),
    ]
